name: Verify and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NODE_ENV: test
jobs:

  # Verify code
  verify:
    name: Verify code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm install
      - run: npm run verify
